/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package arsipsistem;

import java.awt.GridLayout;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.PLAIN_MESSAGE;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tam
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Produkk
     */
    
    public Home() {
        initComponents();
        loadTabelProduk();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbProdukk = new javax.swing.JTable();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        txtCari = new javax.swing.JLabel();
        txtCarii = new javax.swing.JTextField();
        btnReload = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbProdukk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(tbProdukk);

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        txtCari.setText("Cari : ");

        txtCarii.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCariiKeyPressed(evt);
            }
        });

        btnReload.setText("Reload");
        btnReload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReloadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUbah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCari)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCarii))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnReload)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTambah)
                            .addComponent(btnUbah)
                            .addComponent(btnHapus))
                        .addGap(24, 24, 24))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCarii, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCari)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReload)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
       
       // JTextField txtNama = new JTextField(15);
        //JTextField txtHarga = new JTextField(15);
        
//        JPanel myPanel = new JPanel();
  //      myPanel.setLayout(new GridLayout(2,2,0,10));
    //    myPanel.add(new JLabel("Username"));
     //   myPanel.add(txtNama);
      //  myPanel.add(new JLabel("file"));
       // myPanel.add(txtHarga);
        new Kripto_UI().setVisible(true);
        this.dispose();
       // int result = JOptionPane.showConfirmDialog(this, myPanel, 
         //       "Input File Baru",
           //     JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        
      //  if (result == JOptionPane.OK_OPTION) {
        //    try {
          //      Statement stmt = conn.createStatement();
            //    stmt.executeUpdate("INSERT INTO arsip(username,file)" +
             //           " VALUES('" + txtNama.getText() + "', '" +
              //          txtHarga.getText() + "')");
               // loadTabelProduk();
           // } catch (SQLException e) {
             //   System.out.println(e.getMessage());
            //}
        //}
    }//GEN-LAST:event_btnTambahActionPerformed
int selectedID;
    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        if(tbProdukk.isRowSelected(tbProdukk.getSelectedRow())==true){
        selectedID = (int) tbProdukk.getValueAt(tbProdukk.getSelectedRow(),0);
        JTextField txtNama = new JTextField(15);
        JTextField txtHarga = new JTextField(15);
        txtNama.setText(tbProdukk.getValueAt(tbProdukk.getSelectedRow(),1).toString());
        txtHarga.setText(tbProdukk.getValueAt(tbProdukk.getSelectedRow(),2).toString());
        JPanel myPanel = new JPanel();
        myPanel.setLayout(new GridLayout(2,2,0,10));
        myPanel.add(new JLabel ("Username"));
        myPanel.add(txtNama);
        myPanel.add(new JLabel("File"));
        myPanel.add(txtHarga);
        
        int result = JOptionPane.showConfirmDialog(this, myPanel,
                "Ubah file",
                JOptionPane.OK_CANCEL_OPTION,JOptionPane.PLAIN_MESSAGE);
        if (result == JOptionPane.OK_OPTION){
            try{
                Statement stmt = conn.createStatement();
                stmt.executeUpdate("UPDATE arsip SET username='"
                + txtNama.getText()+"', file='"
                + txtHarga.getText() + "'WHERE id_file='"
                + selectedID+"'");
            loadTabelProduk();
            }catch (SQLException e){
                System.out.println(e.getMessage());
            }
        }
        } else {
            JOptionPane.showConfirmDialog(this,"Tidak ada yang dipilih");
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        if(tbProdukk.isRowSelected(tbProdukk.getSelectedRow())==true){
        selectedID = (int) tbProdukk.getValueAt(tbProdukk.getSelectedRow(),0);
        int result = JOptionPane.showConfirmDialog(
                this,
                "Kamu akan menghapus data" + tbProdukk.getValueAt(tbProdukk.getSelectedRow(),1).toString(),"Peringatan!",JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
                );
        if (result == JOptionPane.YES_OPTION){
            try {
                Statement stmt = conn.createStatement();
                stmt.executeUpdate("DELETE FROM arsip WHERE id_file='"
                + selectedID + "'");
                
                loadTabelProduk();
            } catch (SQLException e){
                System.out.println(e.getMessage());
            }
        }
         else {
                JOptionPane.showConfirmDialog(this,"Tidak ada yang dipilih");
                }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void txtCariiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariiKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()== KeyEvent.VK_ENTER){
            String teks = txtCarii.getText();
            loadTabelProduk(teks);
        }
    }//GEN-LAST:event_txtCariiKeyPressed

    private void btnReloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReloadActionPerformed
        // TODO add your handling code here:
        loadTabelProduk();
    }//GEN-LAST:event_btnReloadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

     Connection conn = Koneksi2.connectDB();
     public void loadTabelProduk(String teks){
       
        String sql = "SELECT * FROM arsip WHERE username like '%"+teks+"%'";
        Object[] kolom = {"ID", "Username", "File"};
        DefaultTableModel dataModel = new DefaultTableModel(null, kolom);
        tbProdukk.setModel(dataModel);
        tbProdukk.getColumnModel().getColumn(0).setMaxWidth(30);
        try{
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            while (rs.next()){
                int id = rs.getInt("id_file");
                String nama = rs.getString("username");
                String harga = rs.getString("file");
                
                Object[] data={id,nama,harga};
                dataModel.addRow(data);
            }
         } catch (SQLException e){
             System.out.println(e.getMessage());
         }
        
    }
    public void loadTabelProduk(){
       
        String sql = "SELECT * FROM arsip";
        Object[] kolom = {"ID", "Username", "File"};
        DefaultTableModel dataModel = new DefaultTableModel(null, kolom);
        tbProdukk.setModel(dataModel);
        tbProdukk.getColumnModel().getColumn(0).setMaxWidth(30);
        try{
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            while (rs.next()){
                int id = rs.getInt("id_file");
                String nama = rs.getString("username");
                String harga = rs.getString("file");
                
                Object[] data={id,nama,harga};
                dataModel.addRow(data);
            }
         } catch (SQLException e){
             System.out.println(e.getMessage());
         }
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnReload;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbProdukk;
    private javax.swing.JLabel txtCari;
    private javax.swing.JTextField txtCarii;
    // End of variables declaration//GEN-END:variables
}
