/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package arsipsistem;

import arsipsistem.AES256;
import java.io.File;
import javax.swing.JOptionPane;
import javax.swing.plaf.FileChooserUI;

/**
 *
 * @author tam
 */
public class Kripto_UI extends javax.swing.JFrame {

    /**
     * Creates new form Kripto_UI
     */
    public Kripto_UI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        btnChoose = new javax.swing.JButton();
        txtFIle = new javax.swing.JTextField();
        btnEncrypt = new javax.swing.JButton();
        btnDecrypt = new javax.swing.JButton();
        chkRemove = new javax.swing.JCheckBox();
        btnKembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnChoose.setText("Pilih");
        btnChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseActionPerformed(evt);
            }
        });

        btnEncrypt.setText("Enkripsi");
        btnEncrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncryptActionPerformed(evt);
            }
        });

        btnDecrypt.setText("Dekripsi");
        btnDecrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecryptActionPerformed(evt);
            }
        });

        chkRemove.setText("Hapus file asli ?");

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKembali)
                    .addComponent(chkRemove)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtFIle, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEncrypt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDecrypt)))
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnChoose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtFIle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkRemove)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEncrypt)
                    .addComponent(btnDecrypt))
                .addGap(18, 18, 18)
                .addComponent(btnKembali)
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        File myfile;
        String fileName;
    private void btnChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseActionPerformed
        // TODO add your handling code here:
        try {
           fileChooser.showOpenDialog(null);
           myfile = fileChooser.getSelectedFile();
           fileName = myfile.getAbsolutePath();
           txtFIle.setText(fileName);
           txtFIle.setEnabled(true);
        } catch (Exception e) {
            System.out.println("Canceled : "+e.getMessage());
        }
    }//GEN-LAST:event_btnChooseActionPerformed

    private void btnEncryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncryptActionPerformed
        // TODO add your handling code here:
        String keyInput =  JOptionPane.showInputDialog(this, "Input kunci : ", "Input kunci", JOptionPane.OK_CANCEL_OPTION);
        if (keyInput!=null) {
            String myFilePath = myfile.getAbsolutePath();
            File encryptedFile =  new File(myFilePath+".enc");
            
            boolean p = false;
            try {
                p = AES256.encryptFile(keyInput, myfile, encryptedFile);
                if (p == false) {
                    JOptionPane.showMessageDialog(this, "File ggagal dienkrip");
                } else {
                    JOptionPane.showMessageDialog(this, "FIle telah dienkrip"+encryptedFile.getAbsolutePath());
                }
                if (p== true && chkRemove.isSelected()) {
                myfile.delete();
                }
            } catch (Exception e) {
                System.out.println(e.getMessage());
            } finally {
            System.out.println("done");
            chkRemove.setSelected(false);
            }
        }else {
            System.out.println("dibatalkan");
        }
    }//GEN-LAST:event_btnEncryptActionPerformed

    private void btnDecryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecryptActionPerformed
        // TODO add your handling code here:
        String keyInput =  JOptionPane.showInputDialog(this, "Input kunci : ", "Input kunci", JOptionPane.OK_CANCEL_OPTION);
        if (keyInput!=null) {
            String myFilePath = myfile.getAbsolutePath();
            String decryptedFilePath = myFilePath.substring(0,myFilePath.length()-4);
            File decryptedFile =  new File(decryptedFilePath);
            
            boolean p = false;
            try {
                p = AES256.decryptFile(keyInput, myfile, decryptedFile);
                
                if (p == false) {
                    JOptionPane.showMessageDialog(this, "File ggagal didekrip");
                } else {
                    JOptionPane.showMessageDialog(this, "FIle telah didekrip"+ decryptedFile.getAbsolutePath());
                }
                if (p== true && chkRemove.isSelected()) {
                myfile.delete();
                }
            } catch (Exception e) {
                System.out.println(e.getMessage());
            } finally {
            System.out.println("done");
            chkRemove.setSelected(false);
            }
        }else {
            System.out.println("dibatalkan");
        }
    }//GEN-LAST:event_btnDecryptActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        new Home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kripto_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kripto_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kripto_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kripto_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kripto_UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChoose;
    private javax.swing.JButton btnDecrypt;
    private javax.swing.JButton btnEncrypt;
    private javax.swing.JButton btnKembali;
    private javax.swing.JCheckBox chkRemove;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JTextField txtFIle;
    // End of variables declaration//GEN-END:variables
}
